print("Reglas del Poker")
print("=================")
print()

print("Objetivo:")
print("---------")
print("El objetivo del Poker es formar la mejor combinación de cartas posible.")
print()

print("Carteras:")
print("---------")
print("Cada jugador recibe 5 cartas al azar del mazo.")
print("Las cartas se clasifican en orden descendente:")
print("- Escalera real (mismo palo)")
print("- Escalera de color (mismo palo)")
print("- Poker (4 cartas del mismo valor)")
print("- Full (3 cartas del mismo valor y 2 del mismo valor diferente)")
print("- Color (5 cartas del mismo palo)")
print("- Escalera (5 cartas consecutivas de diferentes palos)")
print("- Tercia (3 cartas del mismo valor)")
print("- Doble pareja (2 cartas del mismo valor y otras 2 del mismo valor diferente)")
print("- Pareja (2 cartas del mismo valor)")
print("- Carta más alta")
print()

print("Rondas:")
print("-------")
print("1. Reparto de cartas")
print("2. Ronda de apuestas")
print("3. Intercambio de cartas (opcional)")
print("4. Ronda de apuestas")
print("5. Mostrar cartas y determinar el ganador")
print()

print("Apuestas:")
print("---------")
print("- Ante: Apuesta inicial obligatoria antes de recibir las cartas.")
print("- Apostar (Bet): Apostar una cantidad determinada.")
print("- Subir (Raise): Igualar la apuesta más alta y aumentarla.")
print("- Igualar (Call): Igualar la apuesta más alta.")
print("- Retirarse (Fold): Abandonar la mano actual.")
print()

print("El jugador con la mejor combinación de cartas gana el bote.")
print("¡Que te diviertas jugando al Poker!")