print("Crea un archivo \"ejercicio_01.py\", añade")
print("un comentario con la descripción del ejercicio \"1\" ")
print("y crea un cuadrado con prints ")      
print("********")
print("*      *")
print("*      *")
print("*      *")
print("********")
